#!/usr/bin/env bash

echo "Please click on the 'sent' window"

pid=$(xdotool selectwindow)

lastfile="$0"
cfile=""

echo "Found 'sent' window $pid"

id=0

mkdir "export"

cycle () {
	id=$((++id));
	cfile="./export/slide-$id.png";
	maim -i "$pid" "$cfile";

	DIFF=$(diff "$lastfile" "$cfile")

	if [ "$DIFF" = "" ]
	then
		rm "$cfile"
		echo "Finished Export"
		exit;
	fi

	lastfile="$cfile"

	xdotool key --window "$pid" Right
}

while true; do
	cycle;
done


