#!/bin/bash

if [[ -z "$@" ]]; then
    echo >&2 "You must supply an argument!"
    exit 1
elif [[ ! -d "$@" ]]; then
    echo >&2 "$@ is not a valid directory!"
    exit 1
fi

echo "Directory $@ was selected"

echo "Please click on the 'sent' window"

pid=$(xdotool selectwindow)

lastfile="/dev/null"
cfile=""

echo "Found 'sent' window $pid"

id=0

rm -rf "$@/*"

cycle () {
	id=$((++id));
	cfile="./export/slide-$id.png";
	maim --hidecursor -i "$pid" "$cfile";

	DIFF=$(diff "$lastfile" "$cfile")

	if [ -z "$DIFF" ]
	then
		rm "$cfile"
		echo "Finished Export"
		exit;
	fi

	lastfile="$cfile"

	xdotool key --window "$pid" Right
}

while true; do
	cycle;
done
